# Generated by Django 4.0.2 on 2022-06-07 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='listhing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('num_bedroom', models.IntegerField()),
                ('num_bathroom', models.IntegerField()),
                ('square_footage', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
            ],
        ),
    ]
