# Generated by Django 4.0.5 on 2022-06-18 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listhing',
            name='address',
        ),
        migrations.RemoveField(
            model_name='listhing',
            name='num_bathroom',
        ),
        migrations.RemoveField(
            model_name='listhing',
            name='num_bedroom',
        ),
        migrations.RemoveField(
            model_name='listhing',
            name='price',
        ),
        migrations.RemoveField(
            model_name='listhing',
            name='square_footage',
        ),
        migrations.AddField(
            model_name='listhing',
            name='choices',
            field=models.PositiveSmallIntegerField(choices=[('mountain', 'M'), ('wlakon', 'W')], default=True, null=True),
        ),
        migrations.AddField(
            model_name='listhing',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='listhing',
            name='discription',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='listhing',
            name='image',
            field=models.ImageField(null=True, upload_to='myimage'),
        ),
        migrations.AlterField(
            model_name='listhing',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
