# Generated by Django 4.0.5 on 2022-06-18 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_remove_listhing_address_remove_listhing_num_bathroom_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photocategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='listhing',
            name='choices',
        ),
        migrations.AddField(
            model_name='listhing',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='social.photocategory'),
        ),
    ]
